// ============================================================================
// Module:       build (build script)
// Description:  Embeds the Windows resources — the application icon Explorer,
//               the taskbar and Task Manager read off the executable.
//
// Dependencies: winresource (Windows only)
// ============================================================================

//! Embeds the application icon into the Windows executables.
//!
//! `eframe` sets a window icon at runtime, which covers the title bar and
//! the running window — but Explorer, the taskbar and Task Manager read
//! an icon *resource* out of the `.exe` itself, and a binary without one
//! shows the generic blank-page icon everywhere it is not running.
//!
//! The icon comes from `assets/brand/icon.ico`, generated by
//! `cargo run --example brand_assets` from the single definition in
//! `src/brand.rs` — do not hand-edit it.
//!
//! Non-Windows builds do nothing here: the concept does not exist, and
//! the desktop entry that plays this role on Linux is packaging rather
//! than a build step.

fn main() {
    // Re-run only when the icon or this script changes, rather than on
    // every source edit.
    println!("cargo:rerun-if-changed=assets/brand/icon.ico");
    println!("cargo:rerun-if-changed=build.rs");

    #[cfg(windows)]
    embed_icon();
}

#[cfg(windows)]
fn embed_icon() {
    let mut resource = winresource::WindowsResource::new();
    resource.set_icon("assets/brand/icon.ico");
    if let Err(error) = resource.compile() {
        // A warning rather than a failure: a missing resource compiler
        // should cost the icon, not the build. Anyone who needs the icon
        // will see this line, and CI builds the release binaries on a
        // runner that has one.
        println!("cargo:warning=could not embed the application icon: {error}");
    }
}
